#!/usr/bin/env node

const cloudinary = require('cloudinary');

const cloudName = 'fragaria';
const uploadPresetName = 'website-posts';
const rootFolder = 'fragaria.cz';

function upload(filePath) {
    return new Promise((resolve, reject) => {
        cloudinary.v2.uploader.unsigned_upload(filePath, uploadPresetName, {cloud_name: cloudName}, (err, result) => {
            if (err) {
                return reject(err);
            }
            return resolve(result);
        })
    });
}

require('yargs') // eslint-disable-line
    .command('upload <file>', 'upload post image to Cloudinary', yargs => {
        yargs
            .positional('file', {
                describe: 'path to your image file',
                type: 'string',
            })
    }, (argv) => {
        if (argv.verbose) {
            console.info(`Uploading image ${argv.file}`);
        }

        upload(argv.file)
            .then(result => {
                console.log('Upload successful.');
                console.log('Public ID: ', result.public_id.replace(`${rootFolder}/`, ''));
            })
            .catch(err => {
                console.error('Upload failed with error: ', err);
            })
    })
    .option('verbose', {
        alias: 'v',
        default: false
    })
    .argv;
